import java.awt.*;
import java.util.Dictionary;
import java.util.Hashtable;

public class NamedColors {
	private static Dictionary<String, Color> namedColors = new Hashtable<String, Color>();

	static {
		namedColors.put("black", new Color(0x000000));
		namedColors.put("navy blue", new Color(0x000080));
		namedColors.put("dark blue", new Color(0x0000c8));
		namedColors.put("blue", new Color(0x0000ff));
		namedColors.put("stratos", new Color(0x000741));
		namedColors.put("swamp", new Color(0x001b1c));
		namedColors.put("resolution blue", new Color(0x002387));
		namedColors.put("deep fir", new Color(0x002900));
		namedColors.put("burnham", new Color(0x002e20));
		namedColors.put("international klein blue", new Color(0x002fa7));
		namedColors.put("prussian blue", new Color(0x003153));
		namedColors.put("midnight blue", new Color(0x003366));
		namedColors.put("smalt", new Color(0x003399));
		namedColors.put("deep teal", new Color(0x003532));
		namedColors.put("cyprus", new Color(0x003e40));
		namedColors.put("kaitoke green", new Color(0x004620));
		namedColors.put("cobalt", new Color(0x0047ab));
		namedColors.put("crusoe", new Color(0x004816));
		namedColors.put("sherpa blue", new Color(0x004950));
		namedColors.put("endeavour", new Color(0x0056a7));
		namedColors.put("camarone", new Color(0x00581a));
		namedColors.put("science blue", new Color(0x0066cc));
		namedColors.put("blue ribbon", new Color(0x0066ff));
		namedColors.put("tropical rain forest", new Color(0x00755e));
		namedColors.put("allports", new Color(0x0076a3));
		namedColors.put("deep cerulean", new Color(0x007ba7));
		namedColors.put("lochmara", new Color(0x007ec7));
		namedColors.put("azure radiance", new Color(0x007fff));
		namedColors.put("teal", new Color(0x008080));
		namedColors.put("bondi blue", new Color(0x0095b6));
		namedColors.put("pacific blue", new Color(0x009dc4));
		namedColors.put("persian green", new Color(0x00a693));
		namedColors.put("jade", new Color(0x00a86b));
		namedColors.put("caribbean green", new Color(0x00cc99));
		namedColors.put("robin's egg blue", new Color(0x00cccc));
		namedColors.put("green", new Color(0x00ff00));
		namedColors.put("spring green", new Color(0x00ff7f));
		namedColors.put("cyan / aqua", new Color(0x00ffff));
		namedColors.put("blue charcoal", new Color(0x010d1a));
		namedColors.put("midnight", new Color(0x011635));
		namedColors.put("holly", new Color(0x011d13));
		namedColors.put("daintree", new Color(0x012731));
		namedColors.put("cardin green", new Color(0x01361c));
		namedColors.put("county green", new Color(0x01371a));
		namedColors.put("astronaut blue", new Color(0x013e62));
		namedColors.put("regal blue", new Color(0x013f6a));
		namedColors.put("aqua deep", new Color(0x014b43));
		namedColors.put("orient", new Color(0x015e85));
		namedColors.put("blue stone", new Color(0x016162));
		namedColors.put("fun green", new Color(0x016d39));
		namedColors.put("pine green", new Color(0x01796f));
		namedColors.put("blue lagoon", new Color(0x017987));
		namedColors.put("deep sea", new Color(0x01826b));
		namedColors.put("green haze", new Color(0x01a368));
		namedColors.put("english holly", new Color(0x022d15));
		namedColors.put("sherwood green", new Color(0x02402c));
		namedColors.put("congress blue", new Color(0x02478e));
		namedColors.put("evening sea", new Color(0x024e46));
		namedColors.put("bahama blue", new Color(0x026395));
		namedColors.put("observatory", new Color(0x02866f));
		namedColors.put("cerulean", new Color(0x02a4d3));
		namedColors.put("tangaroa", new Color(0x03163c));
		namedColors.put("green vogue", new Color(0x032b52));
		namedColors.put("mosque", new Color(0x036a6e));
		namedColors.put("midnight moss", new Color(0x041004));
		namedColors.put("black pearl", new Color(0x041322));
		namedColors.put("blue whale", new Color(0x042e4c));
		namedColors.put("zuccini", new Color(0x044022));
		namedColors.put("teal blue", new Color(0x044259));
		namedColors.put("deep cove", new Color(0x051040));
		namedColors.put("gulf blue", new Color(0x051657));
		namedColors.put("venice blue", new Color(0x055989));
		namedColors.put("watercourse", new Color(0x056f57));
		namedColors.put("catalina blue", new Color(0x062a78));
		namedColors.put("tiber", new Color(0x063537));
		namedColors.put("gossamer", new Color(0x069b81));
		namedColors.put("niagara", new Color(0x06a189));
		namedColors.put("tarawera", new Color(0x073a50));
		namedColors.put("jaguar", new Color(0x080110));
		namedColors.put("black bean", new Color(0x081910));
		namedColors.put("deep sapphire", new Color(0x082567));
		namedColors.put("elf green", new Color(0x088370));
		namedColors.put("bright turquoise", new Color(0x08e8de));
		namedColors.put("downriver", new Color(0x092256));
		namedColors.put("palm green", new Color(0x09230f));
		namedColors.put("madison", new Color(0x09255d));
		namedColors.put("bottle green", new Color(0x093624));
		namedColors.put("deep sea green", new Color(0x095859));
		namedColors.put("salem", new Color(0x097f4b));
		namedColors.put("black russian", new Color(0x0a001c));
		namedColors.put("dark fern", new Color(0x0a480d));
		namedColors.put("japanese laurel", new Color(0x0a6906));
		namedColors.put("atoll", new Color(0x0a6f75));
		namedColors.put("cod gray", new Color(0x0b0b0b));
		namedColors.put("marshland", new Color(0x0b0f08));
		namedColors.put("gordons green", new Color(0x0b1107));
		namedColors.put("black forest", new Color(0x0b1304));
		namedColors.put("san felix", new Color(0x0b6207));
		namedColors.put("malachite", new Color(0x0bda51));
		namedColors.put("ebony", new Color(0x0c0b1d));
		namedColors.put("woodsmoke", new Color(0x0c0d0f));
		namedColors.put("racing green", new Color(0x0c1911));
		namedColors.put("surfie green", new Color(0x0c7a79));
		namedColors.put("blue chill", new Color(0x0c8990));
		namedColors.put("black rock", new Color(0x0d0332));
		namedColors.put("bunker", new Color(0x0d1117));
		namedColors.put("aztec", new Color(0x0d1c19));
		namedColors.put("bush", new Color(0x0d2e1c));
		namedColors.put("cinder", new Color(0x0e0e18));
		namedColors.put("firefly", new Color(0x0e2a30));
		namedColors.put("torea bay", new Color(0x0f2d9e));
		namedColors.put("vulcan", new Color(0x10121d));
		namedColors.put("green waterloo", new Color(0x101405));
		namedColors.put("eden", new Color(0x105852));
		namedColors.put("arapawa", new Color(0x110c6c));
		namedColors.put("ultramarine", new Color(0x120a8f));
		namedColors.put("elephant", new Color(0x123447));
		namedColors.put("jewel", new Color(0x126b40));
		namedColors.put("diesel", new Color(0x130000));
		namedColors.put("asphalt", new Color(0x130a06));
		namedColors.put("blue zodiac", new Color(0x13264d));
		namedColors.put("parsley", new Color(0x134f19));
		namedColors.put("nero", new Color(0x140600));
		namedColors.put("tory blue", new Color(0x1450aa));
		namedColors.put("bunting", new Color(0x151f4c));
		namedColors.put("denim", new Color(0x1560bd));
		namedColors.put("genoa", new Color(0x15736b));
		namedColors.put("mirage", new Color(0x161928));
		namedColors.put("hunter green", new Color(0x161d10));
		namedColors.put("big stone", new Color(0x162a40));
		namedColors.put("celtic", new Color(0x163222));
		namedColors.put("timber green", new Color(0x16322c));
		namedColors.put("gable green", new Color(0x163531));
		namedColors.put("pine tree", new Color(0x171f04));
		namedColors.put("chathams blue", new Color(0x175579));
		namedColors.put("deep forest green", new Color(0x182d09));
		namedColors.put("blumine", new Color(0x18587a));
		namedColors.put("palm leaf", new Color(0x19330e));
		namedColors.put("nile blue", new Color(0x193751));
		namedColors.put("fun blue", new Color(0x1959a8));
		namedColors.put("lucky point", new Color(0x1a1a68));
		namedColors.put("mountain meadow", new Color(0x1ab385));
		namedColors.put("tolopea", new Color(0x1b0245));
		namedColors.put("haiti", new Color(0x1b1035));
		namedColors.put("deep koamaru", new Color(0x1b127b));
		namedColors.put("acadia", new Color(0x1b1404));
		namedColors.put("seaweed", new Color(0x1b2f11));
		namedColors.put("biscay", new Color(0x1b3162));
		namedColors.put("matisse", new Color(0x1b659d));
		namedColors.put("crowshead", new Color(0x1c1208));
		namedColors.put("rangoon green", new Color(0x1c1e13));
		namedColors.put("persian blue", new Color(0x1c39bb));
		namedColors.put("everglade", new Color(0x1c402e));
		namedColors.put("elm", new Color(0x1c7c7d));
		namedColors.put("green pea", new Color(0x1d6142));
		namedColors.put("creole", new Color(0x1e0f04));
		namedColors.put("karaka", new Color(0x1e1609));
		namedColors.put("el paso", new Color(0x1e1708));
		namedColors.put("cello", new Color(0x1e385b));
		namedColors.put("te papa green", new Color(0x1e433c));
		namedColors.put("dodger blue", new Color(0x1e90ff));
		namedColors.put("eastern blue", new Color(0x1e9ab0));
		namedColors.put("night rider", new Color(0x1f120f));
		namedColors.put("java", new Color(0x1fc2c2));
		namedColors.put("jacksons purple", new Color(0x20208d));
		namedColors.put("cloud burst", new Color(0x202e54));
		namedColors.put("blue dianne", new Color(0x204852));
		namedColors.put("eternity", new Color(0x211a0e));
		namedColors.put("deep blue", new Color(0x220878));
		namedColors.put("forest green", new Color(0x228b22));
		namedColors.put("mallard", new Color(0x233418));
		namedColors.put("violet", new Color(0x240a40));
		namedColors.put("kilamanjaro", new Color(0x240c02));
		namedColors.put("log cabin", new Color(0x242a1d));
		namedColors.put("black olive", new Color(0x242e16));
		namedColors.put("green house", new Color(0x24500f));
		namedColors.put("graphite", new Color(0x251607));
		namedColors.put("cannon black", new Color(0x251706));
		namedColors.put("port gore", new Color(0x251f4f));
		namedColors.put("shark", new Color(0x25272c));
		namedColors.put("green kelp", new Color(0x25311c));
		namedColors.put("curious blue", new Color(0x2596d1));
		namedColors.put("paua", new Color(0x260368));
		namedColors.put("paris m", new Color(0x26056a));
		namedColors.put("wood bark", new Color(0x261105));
		namedColors.put("gondola", new Color(0x261414));
		namedColors.put("steel gray", new Color(0x262335));
		namedColors.put("ebony clay", new Color(0x26283b));
		namedColors.put("bay of many", new Color(0x273a81));
		namedColors.put("plantation", new Color(0x27504b));
		namedColors.put("eucalyptus", new Color(0x278a5b));
		namedColors.put("oil", new Color(0x281e15));
		namedColors.put("astronaut", new Color(0x283a77));
		namedColors.put("mariner", new Color(0x286acd));
		namedColors.put("violent violet", new Color(0x290c5e));
		namedColors.put("bastille", new Color(0x292130));
		namedColors.put("zeus", new Color(0x292319));
		namedColors.put("charade", new Color(0x292937));
		namedColors.put("jelly bean", new Color(0x297b9a));
		namedColors.put("jungle green", new Color(0x29ab87));
		namedColors.put("cherry pie", new Color(0x2a0359));
		namedColors.put("coffee bean", new Color(0x2a140e));
		namedColors.put("baltic sea", new Color(0x2a2630));
		namedColors.put("turtle green", new Color(0x2a380b));
		namedColors.put("cerulean blue", new Color(0x2a52be));
		namedColors.put("sepia black", new Color(0x2b0202));
		namedColors.put("valhalla", new Color(0x2b194f));
		namedColors.put("heavy metal", new Color(0x2b3228));
		namedColors.put("blue gem", new Color(0x2c0e8c));
		namedColors.put("revolver", new Color(0x2c1632));
		namedColors.put("bleached cedar", new Color(0x2c2133));
		namedColors.put("lochinvar", new Color(0x2c8c84));
		namedColors.put("mikado", new Color(0x2d2510));
		namedColors.put("outer space", new Color(0x2d383a));
		namedColors.put("st tropaz", new Color(0x2d569b));
		namedColors.put("jacaranda", new Color(0x2e0329));
		namedColors.put("jacko bean", new Color(0x2e1905));
		namedColors.put("rangitoto", new Color(0x2e3222));
		namedColors.put("rhino", new Color(0x2e3f62));
		namedColors.put("sea green", new Color(0x2e8b57));
		namedColors.put("scooter", new Color(0x2ebfd4));
		namedColors.put("onion", new Color(0x2f270e));
		namedColors.put("governor bay", new Color(0x2f3cb3));
		namedColors.put("sapphire", new Color(0x2f519e));
		namedColors.put("spectra", new Color(0x2f5a57));
		namedColors.put("casal", new Color(0x2f6168));
		namedColors.put("melanzane", new Color(0x300529));
		namedColors.put("cocoa brown", new Color(0x301f1e));
		namedColors.put("woodrush", new Color(0x302a0f));
		namedColors.put("san juan", new Color(0x304b6a));
		namedColors.put("turquoise", new Color(0x30d5c8));
		namedColors.put("eclipse", new Color(0x311c17));
		namedColors.put("pickled bluewood", new Color(0x314459));
		namedColors.put("azure", new Color(0x315ba1));
		namedColors.put("calypso", new Color(0x31728d));
		namedColors.put("paradiso", new Color(0x317d82));
		namedColors.put("persian indigo", new Color(0x32127a));
		namedColors.put("blackcurrant", new Color(0x32293a));
		namedColors.put("mine shaft", new Color(0x323232));
		namedColors.put("stromboli", new Color(0x325d52));
		namedColors.put("bilbao", new Color(0x327c14));
		namedColors.put("astral", new Color(0x327da0));
		namedColors.put("christalle", new Color(0x33036b));
		namedColors.put("thunder", new Color(0x33292f));
		namedColors.put("shamrock", new Color(0x33cc99));
		namedColors.put("tamarind", new Color(0x341515));
		namedColors.put("mardi gras", new Color(0x350036));
		namedColors.put("valentino", new Color(0x350e42));
		namedColors.put("jagger", new Color(0x350e57));
		namedColors.put("tuna", new Color(0x353542));
		namedColors.put("chambray", new Color(0x354e8c));
		namedColors.put("martinique", new Color(0x363050));
		namedColors.put("tuatara", new Color(0x363534));
		namedColors.put("waiouru", new Color(0x363c0d));
		namedColors.put("ming", new Color(0x36747d));
		namedColors.put("la palma", new Color(0x368716));
		namedColors.put("chocolate", new Color(0x370202));
		namedColors.put("clinker", new Color(0x371d09));
		namedColors.put("brown tumbleweed", new Color(0x37290e));
		namedColors.put("birch", new Color(0x373021));
		namedColors.put("oracle", new Color(0x377475));
		namedColors.put("blue diamond", new Color(0x380474));
		namedColors.put("grape", new Color(0x381a51));
		namedColors.put("dune", new Color(0x383533));
		namedColors.put("oxford blue", new Color(0x384555));
		namedColors.put("clover", new Color(0x384910));
		namedColors.put("limed spruce", new Color(0x394851));
		namedColors.put("dell", new Color(0x396413));
		namedColors.put("toledo", new Color(0x3a0020));
		namedColors.put("sambuca", new Color(0x3a2010));
		namedColors.put("jacarta", new Color(0x3a2a6a));
		namedColors.put("william", new Color(0x3a686c));
		namedColors.put("killarney", new Color(0x3a6a47));
		namedColors.put("keppel", new Color(0x3ab09e));
		namedColors.put("temptress", new Color(0x3b000b));
		namedColors.put("aubergine", new Color(0x3b0910));
		namedColors.put("jon", new Color(0x3b1f1f));
		namedColors.put("treehouse", new Color(0x3b2820));
		namedColors.put("amazon", new Color(0x3b7a57));
		namedColors.put("boston blue", new Color(0x3b91b4));
		namedColors.put("windsor", new Color(0x3c0878));
		namedColors.put("rebel", new Color(0x3c1206));
		namedColors.put("meteorite", new Color(0x3c1f76));
		namedColors.put("dark ebony", new Color(0x3c2005));
		namedColors.put("camouflage", new Color(0x3c3910));
		namedColors.put("bright gray", new Color(0x3c4151));
		namedColors.put("cape cod", new Color(0x3c4443));
		namedColors.put("lunar green", new Color(0x3c493a));
		namedColors.put("bean  ", new Color(0x3d0c02));
		namedColors.put("bistre", new Color(0x3d2b1f));
		namedColors.put("goblin", new Color(0x3d7d52));
		namedColors.put("kingfisher daisy", new Color(0x3e0480));
		namedColors.put("cedar", new Color(0x3e1c14));
		namedColors.put("english walnut", new Color(0x3e2b23));
		namedColors.put("black marlin", new Color(0x3e2c1c));
		namedColors.put("ship gray", new Color(0x3e3a44));
		namedColors.put("pelorous", new Color(0x3eabbf));
		namedColors.put("bronze", new Color(0x3f2109));
		namedColors.put("cola", new Color(0x3f2500));
		namedColors.put("madras", new Color(0x3f3002));
		namedColors.put("minsk", new Color(0x3f307f));
		namedColors.put("cabbage pont", new Color(0x3f4c3a));
		namedColors.put("tom thumb", new Color(0x3f583b));
		namedColors.put("mineral green", new Color(0x3f5d53));
		namedColors.put("puerto rico", new Color(0x3fc1aa));
		namedColors.put("harlequin", new Color(0x3fff00));
		namedColors.put("brown pod", new Color(0x401801));
		namedColors.put("cork", new Color(0x40291d));
		namedColors.put("masala", new Color(0x403b38));
		namedColors.put("thatch green", new Color(0x403d19));
		namedColors.put("fiord", new Color(0x405169));
		namedColors.put("viridian", new Color(0x40826d));
		namedColors.put("chateau green", new Color(0x40a860));
		namedColors.put("ripe plum", new Color(0x410056));
		namedColors.put("paco", new Color(0x411f10));
		namedColors.put("deep oak", new Color(0x412010));
		namedColors.put("merlin", new Color(0x413c37));
		namedColors.put("gun powder", new Color(0x414257));
		namedColors.put("east bay", new Color(0x414c7d));
		namedColors.put("royal blue", new Color(0x4169e1));
		namedColors.put("ocean green", new Color(0x41aa78));
		namedColors.put("burnt maroon", new Color(0x420303));
		namedColors.put("lisbon brown", new Color(0x423921));
		namedColors.put("faded jade", new Color(0x427977));
		namedColors.put("scarlet gum", new Color(0x431560));
		namedColors.put("iroko", new Color(0x433120));
		namedColors.put("armadillo", new Color(0x433e37));
		namedColors.put("river bed", new Color(0x434c59));
		namedColors.put("green leaf", new Color(0x436a0d));
		namedColors.put("barossa", new Color(0x44012d));
		namedColors.put("morocco brown", new Color(0x441d00));
		namedColors.put("mako", new Color(0x444954));
		namedColors.put("kelp", new Color(0x454936));
		namedColors.put("san marino", new Color(0x456cac));
		namedColors.put("picton blue", new Color(0x45b1e8));
		namedColors.put("loulou", new Color(0x460b41));
		namedColors.put("crater brown", new Color(0x462425));
		namedColors.put("gray asparagus", new Color(0x465945));
		namedColors.put("steel blue", new Color(0x4682b4));
		namedColors.put("rustic red", new Color(0x480404));
		namedColors.put("bulgarian rose", new Color(0x480607));
		namedColors.put("clairvoyant", new Color(0x480656));
		namedColors.put("cocoa bean", new Color(0x481c1c));
		namedColors.put("woody brown", new Color(0x483131));
		namedColors.put("taupe", new Color(0x483c32));
		namedColors.put("van cleef", new Color(0x49170c));
		namedColors.put("brown derby", new Color(0x492615));
		namedColors.put("metallic bronze", new Color(0x49371b));
		namedColors.put("verdun green", new Color(0x495400));
		namedColors.put("blue bayoux", new Color(0x496679));
		namedColors.put("bismark", new Color(0x497183));
		namedColors.put("bracken", new Color(0x4a2a04));
		namedColors.put("deep bronze", new Color(0x4a3004));
		namedColors.put("mondo", new Color(0x4a3c30));
		namedColors.put("tundora", new Color(0x4a4244));
		namedColors.put("gravel", new Color(0x4a444b));
		namedColors.put("trout", new Color(0x4a4e5a));
		namedColors.put("pigment indigo", new Color(0x4b0082));
		namedColors.put("nandor", new Color(0x4b5d52));
		namedColors.put("saddle", new Color(0x4c3024));
		namedColors.put("abbey", new Color(0x4c4f56));
		namedColors.put("blackberry", new Color(0x4d0135));
		namedColors.put("cab sav", new Color(0x4d0a18));
		namedColors.put("indian tan", new Color(0x4d1e01));
		namedColors.put("cowboy", new Color(0x4d282d));
		namedColors.put("livid brown", new Color(0x4d282e));
		namedColors.put("rock", new Color(0x4d3833));
		namedColors.put("punga", new Color(0x4d3d14));
		namedColors.put("bronzetone", new Color(0x4d400f));
		namedColors.put("woodland", new Color(0x4d5328));
		namedColors.put("mahogany", new Color(0x4e0606));
		namedColors.put("bossanova", new Color(0x4e2a5a));
		namedColors.put("matterhorn", new Color(0x4e3b41));
		namedColors.put("bronze olive", new Color(0x4e420c));
		namedColors.put("mulled wine", new Color(0x4e4562));
		namedColors.put("axolotl", new Color(0x4e6649));
		namedColors.put("wedgewood", new Color(0x4e7f9e));
		namedColors.put("shakespeare", new Color(0x4eabd1));
		namedColors.put("honey flower", new Color(0x4f1c70));
		namedColors.put("daisy bush", new Color(0x4f2398));
		namedColors.put("indigo", new Color(0x4f69c6));
		namedColors.put("fern green", new Color(0x4f7942));
		namedColors.put("fruit salad", new Color(0x4f9d5d));
		namedColors.put("apple", new Color(0x4fa83d));
		namedColors.put("mortar", new Color(0x504351));
		namedColors.put("kashmir blue", new Color(0x507096));
		namedColors.put("cutty sark", new Color(0x507672));
		namedColors.put("emerald", new Color(0x50c878));
		namedColors.put("emperor", new Color(0x514649));
		namedColors.put("chalet green", new Color(0x516e3d));
		namedColors.put("como", new Color(0x517c66));
		namedColors.put("smalt blue", new Color(0x51808f));
		namedColors.put("castro", new Color(0x52001f));
		namedColors.put("maroon oak", new Color(0x520c17));
		namedColors.put("gigas", new Color(0x523c94));
		namedColors.put("voodoo", new Color(0x533455));
		namedColors.put("victoria", new Color(0x534491));
		namedColors.put("hippie green", new Color(0x53824b));
		namedColors.put("heath", new Color(0x541012));
		namedColors.put("judge gray", new Color(0x544333));
		namedColors.put("fuscous gray", new Color(0x54534d));
		namedColors.put("vida loca", new Color(0x549019));
		namedColors.put("cioccolato", new Color(0x55280c));
		namedColors.put("saratoga", new Color(0x555b10));
		namedColors.put("finlandia", new Color(0x556d56));
		namedColors.put("havelock blue", new Color(0x5590d9));
		namedColors.put("fountain blue", new Color(0x56b4be));
		namedColors.put("spring leaves", new Color(0x578363));
		namedColors.put("saddle brown", new Color(0x583401));
		namedColors.put("scarpa flow", new Color(0x585562));
		namedColors.put("cactus", new Color(0x587156));
		namedColors.put("hippie blue", new Color(0x589aaf));
		namedColors.put("wine berry", new Color(0x591d35));
		namedColors.put("brown bramble", new Color(0x592804));
		namedColors.put("congo brown", new Color(0x593737));
		namedColors.put("millbrook", new Color(0x594433));
		namedColors.put("waikawa gray", new Color(0x5a6e9c));
		namedColors.put("horizon", new Color(0x5a87a0));
		namedColors.put("jambalaya", new Color(0x5b3013));
		namedColors.put("bordeaux", new Color(0x5c0120));
		namedColors.put("mulberry wood", new Color(0x5c0536));
		namedColors.put("carnaby tan", new Color(0x5c2e01));
		namedColors.put("comet", new Color(0x5c5d75));
		namedColors.put("redwood", new Color(0x5d1e0f));
		namedColors.put("don juan", new Color(0x5d4c51));
		namedColors.put("chicago", new Color(0x5d5c58));
		namedColors.put("verdigris", new Color(0x5d5e37));
		namedColors.put("dingley", new Color(0x5d7747));
		namedColors.put("breaker bay", new Color(0x5da19f));
		namedColors.put("kabul", new Color(0x5e483e));
		namedColors.put("hemlock", new Color(0x5e5d3b));
		namedColors.put("irish coffee", new Color(0x5f3d26));
		namedColors.put("mid gray", new Color(0x5f5f6e));
		namedColors.put("shuttle gray", new Color(0x5f6672));
		namedColors.put("aqua forest", new Color(0x5fa777));
		namedColors.put("tradewind", new Color(0x5fb3ac));
		namedColors.put("horses neck", new Color(0x604913));
		namedColors.put("smoky", new Color(0x605b73));
		namedColors.put("corduroy", new Color(0x606e68));
		namedColors.put("danube", new Color(0x6093d1));
		namedColors.put("espresso", new Color(0x612718));
		namedColors.put("eggplant", new Color(0x614051));
		namedColors.put("costa del sol", new Color(0x615d30));
		namedColors.put("glade green", new Color(0x61845f));
		namedColors.put("buccaneer", new Color(0x622f30));
		namedColors.put("quincy", new Color(0x623f2d));
		namedColors.put("butterfly bush", new Color(0x624e9a));
		namedColors.put("west coast", new Color(0x625119));
		namedColors.put("finch", new Color(0x626649));
		namedColors.put("patina", new Color(0x639a8f));
		namedColors.put("fern", new Color(0x63b76c));
		namedColors.put("blue violet", new Color(0x6456b7));
		namedColors.put("dolphin", new Color(0x646077));
		namedColors.put("storm dust", new Color(0x646463));
		namedColors.put("siam", new Color(0x646a54));
		namedColors.put("nevada", new Color(0x646e75));
		namedColors.put("cornflower blue", new Color(0x6495ed));
		namedColors.put("viking", new Color(0x64ccdb));
		namedColors.put("rosewood", new Color(0x65000b));
		namedColors.put("cherrywood", new Color(0x651a14));
		namedColors.put("purple heart", new Color(0x652dc1));
		namedColors.put("fern frond", new Color(0x657220));
		namedColors.put("willow grove", new Color(0x65745d));
		namedColors.put("hoki", new Color(0x65869f));
		namedColors.put("pompadour", new Color(0x660045));
		namedColors.put("purple", new Color(0x660099));
		namedColors.put("tyrian purple", new Color(0x66023c));
		namedColors.put("dark tan", new Color(0x661010));
		namedColors.put("silver tree", new Color(0x66b58f));
		namedColors.put("bright green", new Color(0x66ff00));
		namedColors.put("screamin' green", new Color(0x66ff66));
		namedColors.put("black rose", new Color(0x67032d));
		namedColors.put("scampi", new Color(0x675fa6));
		namedColors.put("ironside gray", new Color(0x676662));
		namedColors.put("viridian green", new Color(0x678975));
		namedColors.put("christi", new Color(0x67a712));
		namedColors.put("nutmeg wood finish", new Color(0x683600));
		namedColors.put("zambezi", new Color(0x685558));
		namedColors.put("salt box", new Color(0x685e6e));
		namedColors.put("tawny port", new Color(0x692545));
		namedColors.put("finn", new Color(0x692d54));
		namedColors.put("scorpion", new Color(0x695f62));
		namedColors.put("lynch", new Color(0x697e9a));
		namedColors.put("spice", new Color(0x6a442e));
		namedColors.put("himalaya", new Color(0x6a5d1b));
		namedColors.put("soya bean", new Color(0x6a6051));
		namedColors.put("hairy heath", new Color(0x6b2a14));
		namedColors.put("royal purple", new Color(0x6b3fa0));
		namedColors.put("shingle fawn", new Color(0x6b4e31));
		namedColors.put("dorado", new Color(0x6b5755));
		namedColors.put("bermuda gray", new Color(0x6b8ba2));
		namedColors.put("olive drab", new Color(0x6b8e23));
		namedColors.put("eminence", new Color(0x6c3082));
		namedColors.put("turquoise blue", new Color(0x6cdae7));
		namedColors.put("lonestar", new Color(0x6d0101));
		namedColors.put("pine cone", new Color(0x6d5e54));
		namedColors.put("dove gray", new Color(0x6d6c6c));
		namedColors.put("juniper", new Color(0x6d9292));
		namedColors.put("gothic", new Color(0x6d92a1));
		namedColors.put("red oxide", new Color(0x6e0902));
		namedColors.put("moccaccino", new Color(0x6e1d14));
		namedColors.put("pickled bean", new Color(0x6e4826));
		namedColors.put("dallas", new Color(0x6e4b26));
		namedColors.put("kokoda", new Color(0x6e6d57));
		namedColors.put("pale sky", new Color(0x6e7783));
		namedColors.put("cafe royale", new Color(0x6f440c));
		namedColors.put("flint", new Color(0x6f6a61));
		namedColors.put("highland", new Color(0x6f8e63));
		namedColors.put("limeade", new Color(0x6f9d02));
		namedColors.put("downy", new Color(0x6fd0c5));
		namedColors.put("persian plum", new Color(0x701c1c));
		namedColors.put("sepia", new Color(0x704214));
		namedColors.put("antique bronze", new Color(0x704a07));
		namedColors.put("ferra", new Color(0x704f50));
		namedColors.put("coffee", new Color(0x706555));
		namedColors.put("slate gray", new Color(0x708090));
		namedColors.put("cedar wood finish", new Color(0x711a00));
		namedColors.put("metallic copper", new Color(0x71291d));
		namedColors.put("affair", new Color(0x714693));
		namedColors.put("studio", new Color(0x714ab2));
		namedColors.put("tobacco brown", new Color(0x715d47));
		namedColors.put("yellow metal", new Color(0x716338));
		namedColors.put("peat", new Color(0x716b56));
		namedColors.put("olivetone", new Color(0x716e10));
		namedColors.put("storm gray", new Color(0x717486));
		namedColors.put("sirocco", new Color(0x718080));
		namedColors.put("aquamarine blue", new Color(0x71d9e2));
		namedColors.put("venetian red", new Color(0x72010f));
		namedColors.put("old copper", new Color(0x724a2f));
		namedColors.put("go ben", new Color(0x726d4e));
		namedColors.put("raven", new Color(0x727b89));
		namedColors.put("seance", new Color(0x731e8f));
		namedColors.put("raw umber", new Color(0x734a12));
		namedColors.put("kimberly", new Color(0x736c9f));
		namedColors.put("crocodile", new Color(0x736d58));
		namedColors.put("crete", new Color(0x737829));
		namedColors.put("xanadu", new Color(0x738678));
		namedColors.put("spicy mustard", new Color(0x74640d));
		namedColors.put("limed ash", new Color(0x747d63));
		namedColors.put("rolling stone", new Color(0x747d83));
		namedColors.put("blue smoke", new Color(0x748881));
		namedColors.put("laurel", new Color(0x749378));
		namedColors.put("mantis", new Color(0x74c365));
		namedColors.put("russett", new Color(0x755a57));
		namedColors.put("deluge", new Color(0x7563a8));
		namedColors.put("cosmic", new Color(0x76395d));
		namedColors.put("blue marguerite", new Color(0x7666c6));
		namedColors.put("lima", new Color(0x76bd17));
		namedColors.put("sky blue", new Color(0x76d7ea));
		namedColors.put("dark burgundy", new Color(0x770f05));
		namedColors.put("crown of thorns", new Color(0x771f1f));
		namedColors.put("walnut", new Color(0x773f1a));
		namedColors.put("pablo", new Color(0x776f61));
		namedColors.put("pacifika", new Color(0x778120));
		namedColors.put("oxley", new Color(0x779e86));
		namedColors.put("pastel green", new Color(0x77dd77));
		namedColors.put("japanese maple", new Color(0x780109));
		namedColors.put("mocha", new Color(0x782d19));
		namedColors.put("peanut", new Color(0x782f16));
		namedColors.put("camouflage green", new Color(0x78866b));
		namedColors.put("wasabi", new Color(0x788a25));
		namedColors.put("ship cove", new Color(0x788bba));
		namedColors.put("sea nymph", new Color(0x78a39c));
		namedColors.put("roman coffee", new Color(0x795d4c));
		namedColors.put("old lavender", new Color(0x796878));
		namedColors.put("rum", new Color(0x796989));
		namedColors.put("fedora", new Color(0x796a78));
		namedColors.put("sandstone", new Color(0x796d62));
		namedColors.put("spray", new Color(0x79deec));
		namedColors.put("siren", new Color(0x7a013a));
		namedColors.put("fuchsia blue", new Color(0x7a58c1));
		namedColors.put("boulder", new Color(0x7a7a7a));
		namedColors.put("wild blue yonder", new Color(0x7a89b8));
		namedColors.put("de york", new Color(0x7ac488));
		namedColors.put("red beech", new Color(0x7b3801));
		namedColors.put("cinnamon", new Color(0x7b3f00));
		namedColors.put("yukon gold", new Color(0x7b6608));
		namedColors.put("tapa", new Color(0x7b7874));
		namedColors.put("waterloo ", new Color(0x7b7c94));
		namedColors.put("flax smoke", new Color(0x7b8265));
		namedColors.put("amulet", new Color(0x7b9f80));
		namedColors.put("asparagus", new Color(0x7ba05b));
		namedColors.put("kenyan copper", new Color(0x7c1c05));
		namedColors.put("pesto", new Color(0x7c7631));
		namedColors.put("topaz", new Color(0x7c778a));
		namedColors.put("concord", new Color(0x7c7b7a));
		namedColors.put("jumbo", new Color(0x7c7b82));
		namedColors.put("trendy green", new Color(0x7c881a));
		namedColors.put("gumbo", new Color(0x7ca1a6));
		namedColors.put("acapulco", new Color(0x7cb0a1));
		namedColors.put("neptune", new Color(0x7cb7bb));
		namedColors.put("pueblo", new Color(0x7d2c14));
		namedColors.put("bay leaf", new Color(0x7da98d));
		namedColors.put("malibu", new Color(0x7dc8f7));
		namedColors.put("bermuda", new Color(0x7dd8c6));
		namedColors.put("copper canyon", new Color(0x7e3a15));
		namedColors.put("claret", new Color(0x7f1734));
		namedColors.put("peru tan", new Color(0x7f3a02));
		namedColors.put("falcon", new Color(0x7f626d));
		namedColors.put("mobster", new Color(0x7f7589));
		namedColors.put("moody blue", new Color(0x7f76d3));
		namedColors.put("chartreuse", new Color(0x7fff00));
		namedColors.put("aquamarine", new Color(0x7fffd4));
		namedColors.put("maroon", new Color(0x800000));
		namedColors.put("rose bud cherry", new Color(0x800b47));
		namedColors.put("falu red", new Color(0x801818));
		namedColors.put("red robin", new Color(0x80341f));
		namedColors.put("vivid violet", new Color(0x803790));
		namedColors.put("russet", new Color(0x80461b));
		namedColors.put("friar gray", new Color(0x807e79));
		namedColors.put("olive", new Color(0x808000));
		namedColors.put("gray", new Color(0x808080));
		namedColors.put("gulf stream", new Color(0x80b3ae));
		namedColors.put("glacier", new Color(0x80b3c4));
		namedColors.put("seagull", new Color(0x80ccea));
		namedColors.put("nutmeg", new Color(0x81422c));
		namedColors.put("spicy pink", new Color(0x816e71));
		namedColors.put("empress", new Color(0x817377));
		namedColors.put("spanish green", new Color(0x819885));
		namedColors.put("sand dune", new Color(0x826f65));
		namedColors.put("gunsmoke", new Color(0x828685));
		namedColors.put("battleship gray", new Color(0x828f72));
		namedColors.put("merlot", new Color(0x831923));
		namedColors.put("shadow", new Color(0x837050));
		namedColors.put("chelsea cucumber", new Color(0x83aa5d));
		namedColors.put("monte carlo", new Color(0x83d0c6));
		namedColors.put("plum", new Color(0x843179));
		namedColors.put("granny smith", new Color(0x84a0a0));
		namedColors.put("chetwode blue", new Color(0x8581d9));
		namedColors.put("bandicoot", new Color(0x858470));
		namedColors.put("bali hai", new Color(0x859faf));
		namedColors.put("half baked", new Color(0x85c4cc));
		namedColors.put("red devil", new Color(0x860111));
		namedColors.put("lotus", new Color(0x863c3c));
		namedColors.put("ironstone", new Color(0x86483c));
		namedColors.put("bull shot", new Color(0x864d1e));
		namedColors.put("rusty nail", new Color(0x86560a));
		namedColors.put("bitter", new Color(0x868974));
		namedColors.put("regent gray", new Color(0x86949f));
		namedColors.put("disco", new Color(0x871550));
		namedColors.put("americano", new Color(0x87756e));
		namedColors.put("hurricane", new Color(0x877c7b));
		namedColors.put("oslo gray", new Color(0x878d91));
		namedColors.put("sushi", new Color(0x87ab39));
		namedColors.put("spicy mix", new Color(0x885342));
		namedColors.put("kumera", new Color(0x886221));
		namedColors.put("suva gray", new Color(0x888387));
		namedColors.put("avocado", new Color(0x888d65));
		namedColors.put("camelot", new Color(0x893456));
		namedColors.put("solid pink", new Color(0x893843));
		namedColors.put("cannon pink", new Color(0x894367));
		namedColors.put("makara", new Color(0x897d6d));
		namedColors.put("burnt umber", new Color(0x8a3324));
		namedColors.put("true v", new Color(0x8a73d6));
		namedColors.put("clay creek", new Color(0x8a8360));
		namedColors.put("monsoon", new Color(0x8a8389));
		namedColors.put("stack", new Color(0x8a8f8a));
		namedColors.put("jordy blue", new Color(0x8ab9f1));
		namedColors.put("electric violet", new Color(0x8b00ff));
		namedColors.put("monarch", new Color(0x8b0723));
		namedColors.put("corn harvest", new Color(0x8b6b0b));
		namedColors.put("olive haze", new Color(0x8b8470));
		namedColors.put("schooner", new Color(0x8b847e));
		namedColors.put("natural gray", new Color(0x8b8680));
		namedColors.put("mantle", new Color(0x8b9c90));
		namedColors.put("portage", new Color(0x8b9fee));
		namedColors.put("envy", new Color(0x8ba690));
		namedColors.put("cascade", new Color(0x8ba9a5));
		namedColors.put("riptide", new Color(0x8be6d8));
		namedColors.put("cardinal pink", new Color(0x8c055e));
		namedColors.put("mule fawn", new Color(0x8c472f));
		namedColors.put("potters clay", new Color(0x8c5738));
		namedColors.put("trendy pink", new Color(0x8c6495));
		namedColors.put("paprika", new Color(0x8d0226));
		namedColors.put("sanguine brown", new Color(0x8d3d38));
		namedColors.put("tosca", new Color(0x8d3f3f));
		namedColors.put("cement", new Color(0x8d7662));
		namedColors.put("granite green", new Color(0x8d8974));
		namedColors.put("manatee", new Color(0x8d90a1));
		namedColors.put("polo blue", new Color(0x8da8cc));
		namedColors.put("red berry", new Color(0x8e0000));
		namedColors.put("rope", new Color(0x8e4d1e));
		namedColors.put("opium", new Color(0x8e6f70));
		namedColors.put("domino", new Color(0x8e775e));
		namedColors.put("mamba", new Color(0x8e8190));
		namedColors.put("nepal", new Color(0x8eabc1));
		namedColors.put("pohutukawa", new Color(0x8f021c));
		namedColors.put("el salva", new Color(0x8f3e33));
		namedColors.put("korma", new Color(0x8f4b0e));
		namedColors.put("squirrel", new Color(0x8f8176));
		namedColors.put("vista blue", new Color(0x8fd6b4));
		namedColors.put("burgundy", new Color(0x900020));
		namedColors.put("old brick", new Color(0x901e1e));
		namedColors.put("hemp", new Color(0x907874));
		namedColors.put("almond frost", new Color(0x907b71));
		namedColors.put("sycamore", new Color(0x908d39));
		namedColors.put("sangria", new Color(0x92000a));
		namedColors.put("cumin", new Color(0x924321));
		namedColors.put("beaver", new Color(0x926f5b));
		namedColors.put("stonewall", new Color(0x928573));
		namedColors.put("venus", new Color(0x928590));
		namedColors.put("medium purple", new Color(0x9370db));
		namedColors.put("cornflower", new Color(0x93ccea));
		namedColors.put("algae green", new Color(0x93dfb8));
		namedColors.put("copper rust", new Color(0x944747));
		namedColors.put("arrowtown", new Color(0x948771));
		namedColors.put("scarlett", new Color(0x950015));
		namedColors.put("strikemaster", new Color(0x956387));
		namedColors.put("mountain mist", new Color(0x959396));
		namedColors.put("carmine", new Color(0x960018));
		namedColors.put("brown", new Color(0x964b00));
		namedColors.put("leather", new Color(0x967059));
		namedColors.put("purple mountain's majesty", new Color(0x9678b6));
		namedColors.put("lavender purple", new Color(0x967bb6));
		namedColors.put("pewter", new Color(0x96a8a1));
		namedColors.put("summer green", new Color(0x96bbab));
		namedColors.put("au chico", new Color(0x97605d));
		namedColors.put("wisteria", new Color(0x9771b5));
		namedColors.put("atlantis", new Color(0x97cd2d));
		namedColors.put("vin rouge", new Color(0x983d61));
		namedColors.put("lilac bush", new Color(0x9874d3));
		namedColors.put("bazaar", new Color(0x98777b));
		namedColors.put("hacienda", new Color(0x98811b));
		namedColors.put("pale oyster", new Color(0x988d77));
		namedColors.put("mint green", new Color(0x98ff98));
		namedColors.put("fresh eggplant", new Color(0x990066));
		namedColors.put("violet eggplant", new Color(0x991199));
		namedColors.put("tamarillo", new Color(0x991613));
		namedColors.put("totem pole", new Color(0x991b07));
		namedColors.put("copper rose", new Color(0x996666));
		namedColors.put("amethyst", new Color(0x9966cc));
		namedColors.put("mountbatten pink", new Color(0x997a8d));
		namedColors.put("blue bell", new Color(0x9999cc));
		namedColors.put("prairie sand", new Color(0x9a3820));
		namedColors.put("toast", new Color(0x9a6e61));
		namedColors.put("gurkha", new Color(0x9a9577));
		namedColors.put("olivine", new Color(0x9ab973));
		namedColors.put("shadow green", new Color(0x9ac2b8));
		namedColors.put("oregon", new Color(0x9b4703));
		namedColors.put("lemon grass", new Color(0x9b9e8f));
		namedColors.put("stiletto", new Color(0x9c3336));
		namedColors.put("hawaiian tan", new Color(0x9d5616));
		namedColors.put("gull gray", new Color(0x9dacb7));
		namedColors.put("pistachio", new Color(0x9dc209));
		namedColors.put("granny smith apple", new Color(0x9de093));
		namedColors.put("anakiwa", new Color(0x9de5ff));
		namedColors.put("chelsea gem", new Color(0x9e5302));
		namedColors.put("sepia skin", new Color(0x9e5b40));
		namedColors.put("sage", new Color(0x9ea587));
		namedColors.put("citron", new Color(0x9ea91f));
		namedColors.put("rock blue", new Color(0x9eb1cd));
		namedColors.put("morning glory", new Color(0x9edee0));
		namedColors.put("cognac", new Color(0x9f381d));
		namedColors.put("reef gold", new Color(0x9f821c));
		namedColors.put("star dust", new Color(0x9f9f9c));
		namedColors.put("santas gray", new Color(0x9fa0b1));
		namedColors.put("sinbad", new Color(0x9fd7d3));
		namedColors.put("feijoa", new Color(0x9fdd8c));
		namedColors.put("tabasco", new Color(0xa02712));
		namedColors.put("buttered rum", new Color(0xa1750d));
		namedColors.put("hit gray", new Color(0xa1adb5));
		namedColors.put("citrus", new Color(0xa1c50a));
		namedColors.put("aqua island", new Color(0xa1dad7));
		namedColors.put("water leaf", new Color(0xa1e9de));
		namedColors.put("flirt", new Color(0xa2006d));
		namedColors.put("rouge", new Color(0xa23b6c));
		namedColors.put("cape palliser", new Color(0xa26645));
		namedColors.put("gray chateau", new Color(0xa2aab3));
		namedColors.put("edward", new Color(0xa2aeab));
		namedColors.put("pharlap", new Color(0xa3807b));
		namedColors.put("amethyst smoke", new Color(0xa397b4));
		namedColors.put("blizzard blue", new Color(0xa3e3ed));
		namedColors.put("delta", new Color(0xa4a49d));
		namedColors.put("wistful", new Color(0xa4a6d3));
		namedColors.put("green smoke", new Color(0xa4af6e));
		namedColors.put("jazzberry jam", new Color(0xa50b5e));
		namedColors.put("zorba", new Color(0xa59b91));
		namedColors.put("bahia", new Color(0xa5cb0c));
		namedColors.put("roof terracotta", new Color(0xa62f20));
		namedColors.put("paarl", new Color(0xa65529));
		namedColors.put("barley corn", new Color(0xa68b5b));
		namedColors.put("donkey brown", new Color(0xa69279));
		namedColors.put("dawn", new Color(0xa6a29a));
		namedColors.put("mexican red", new Color(0xa72525));
		namedColors.put("luxor gold", new Color(0xa7882c));
		namedColors.put("rich gold", new Color(0xa85307));
		namedColors.put("reno sand", new Color(0xa86515));
		namedColors.put("coral tree", new Color(0xa86b6b));
		namedColors.put("dusty gray", new Color(0xa8989b));
		namedColors.put("dull lavender", new Color(0xa899e6));
		namedColors.put("tallow", new Color(0xa8a589));
		namedColors.put("bud", new Color(0xa8ae9c));
		namedColors.put("locust", new Color(0xa8af8e));
		namedColors.put("norway", new Color(0xa8bd9f));
		namedColors.put("chinook", new Color(0xa8e3bd));
		namedColors.put("gray olive", new Color(0xa9a491));
		namedColors.put("aluminium", new Color(0xa9acb6));
		namedColors.put("cadet blue", new Color(0xa9b2c3));
		namedColors.put("schist", new Color(0xa9b497));
		namedColors.put("tower gray", new Color(0xa9bdbf));
		namedColors.put("perano", new Color(0xa9bef2));
		namedColors.put("opal", new Color(0xa9c6c2));
		namedColors.put("night shadz", new Color(0xaa375a));
		namedColors.put("fire", new Color(0xaa4203));
		namedColors.put("muesli", new Color(0xaa8b5b));
		namedColors.put("sandal", new Color(0xaa8d6f));
		namedColors.put("shady lady", new Color(0xaaa5a9));
		namedColors.put("logan", new Color(0xaaa9cd));
		namedColors.put("spun pearl", new Color(0xaaabb7));
		namedColors.put("regent st blue", new Color(0xaad6e6));
		namedColors.put("magic mint", new Color(0xaaf0d1));
		namedColors.put("lipstick", new Color(0xab0563));
		namedColors.put("royal heath", new Color(0xab3472));
		namedColors.put("sandrift", new Color(0xab917a));
		namedColors.put("cold purple", new Color(0xaba0d9));
		namedColors.put("bronco", new Color(0xaba196));
		namedColors.put("limed oak", new Color(0xac8a56));
		namedColors.put("east side", new Color(0xac91ce));
		namedColors.put("lemon ginger", new Color(0xac9e22));
		namedColors.put("napa", new Color(0xaca494));
		namedColors.put("hillary", new Color(0xaca586));
		namedColors.put("cloudy", new Color(0xaca59f));
		namedColors.put("silver chalice", new Color(0xacacac));
		namedColors.put("swamp green", new Color(0xacb78e));
		namedColors.put("spring rain", new Color(0xaccbb1));
		namedColors.put("conifer", new Color(0xacdd4d));
		namedColors.put("celadon", new Color(0xace1af));
		namedColors.put("mandalay", new Color(0xad781b));
		namedColors.put("casper", new Color(0xadbed1));
		namedColors.put("moss green", new Color(0xaddfad));
		namedColors.put("padua", new Color(0xade6c4));
		namedColors.put("green yellow", new Color(0xadff2f));
		namedColors.put("hippie pink", new Color(0xae4560));
		namedColors.put("desert", new Color(0xae6020));
		namedColors.put("bouquet", new Color(0xae809e));
		namedColors.put("medium carmine", new Color(0xaf4035));
		namedColors.put("apple blossom", new Color(0xaf4d43));
		namedColors.put("brown rust", new Color(0xaf593e));
		namedColors.put("driftwood", new Color(0xaf8751));
		namedColors.put("alpine", new Color(0xaf8f2c));
		namedColors.put("lucky", new Color(0xaf9f1c));
		namedColors.put("martini", new Color(0xafa09e));
		namedColors.put("bombay", new Color(0xafb1b8));
		namedColors.put("pigeon post", new Color(0xafbdd9));
		namedColors.put("cadillac", new Color(0xb04c6a));
		namedColors.put("matrix", new Color(0xb05d54));
		namedColors.put("tapestry", new Color(0xb05e81));
		namedColors.put("mai tai", new Color(0xb06608));
		namedColors.put("del rio", new Color(0xb09a95));
		namedColors.put("powder blue", new Color(0xb0e0e6));
		namedColors.put("inch worm", new Color(0xb0e313));
		namedColors.put("bright red", new Color(0xb10000));
		namedColors.put("vesuvius", new Color(0xb14a0b));
		namedColors.put("pumpkin skin", new Color(0xb1610b));
		namedColors.put("santa fe", new Color(0xb16d52));
		namedColors.put("teak", new Color(0xb19461));
		namedColors.put("fringy flower", new Color(0xb1e2c1));
		namedColors.put("ice cold", new Color(0xb1f4e7));
		namedColors.put("shiraz", new Color(0xb20931));
		namedColors.put("biloba flower", new Color(0xb2a1ea));
		namedColors.put("tall poppy", new Color(0xb32d29));
		namedColors.put("fiery orange", new Color(0xb35213));
		namedColors.put("hot toddy", new Color(0xb38007));
		namedColors.put("taupe gray", new Color(0xb3af95));
		namedColors.put("la rioja", new Color(0xb3c110));
		namedColors.put("well read", new Color(0xb43332));
		namedColors.put("blush", new Color(0xb44668));
		namedColors.put("jungle mist", new Color(0xb4cfd3));
		namedColors.put("turkish rose", new Color(0xb57281));
		namedColors.put("lavender", new Color(0xb57edc));
		namedColors.put("mongoose", new Color(0xb5a27f));
		namedColors.put("olive green", new Color(0xb5b35c));
		namedColors.put("jet stream", new Color(0xb5d2ce));
		namedColors.put("cruise", new Color(0xb5ecdf));
		namedColors.put("hibiscus", new Color(0xb6316c));
		namedColors.put("thatch", new Color(0xb69d98));
		namedColors.put("heathered gray", new Color(0xb6b095));
		namedColors.put("eagle", new Color(0xb6baa4));
		namedColors.put("spindle", new Color(0xb6d1ea));
		namedColors.put("gum leaf", new Color(0xb6d3bf));
		namedColors.put("rust", new Color(0xb7410e));
		namedColors.put("muddy waters", new Color(0xb78e5c));
		namedColors.put("sahara", new Color(0xb7a214));
		namedColors.put("husk", new Color(0xb7a458));
		namedColors.put("nobel", new Color(0xb7b1b1));
		namedColors.put("heather", new Color(0xb7c3d0));
		namedColors.put("madang", new Color(0xb7f0be));
		namedColors.put("milano red", new Color(0xb81104));
		namedColors.put("copper", new Color(0xb87333));
		namedColors.put("gimblet", new Color(0xb8b56a));
		namedColors.put("green spring", new Color(0xb8c1b1));
		namedColors.put("celery", new Color(0xb8c25d));
		namedColors.put("sail", new Color(0xb8e0f9));
		namedColors.put("chestnut", new Color(0xb94e48));
		namedColors.put("crail", new Color(0xb95140));
		namedColors.put("marigold", new Color(0xb98d28));
		namedColors.put("wild willow", new Color(0xb9c46a));
		namedColors.put("rainee", new Color(0xb9c8ac));
		namedColors.put("guardsman red", new Color(0xba0101));
		namedColors.put("rock spray", new Color(0xba450c));
		namedColors.put("bourbon", new Color(0xba6f1e));
		namedColors.put("pirate gold", new Color(0xba7f03));
		namedColors.put("nomad", new Color(0xbab1a2));
		namedColors.put("submarine", new Color(0xbac7c9));
		namedColors.put("charlotte", new Color(0xbaeef9));
		namedColors.put("medium red violet", new Color(0xbb3385));
		namedColors.put("brandy rose", new Color(0xbb8983));
		namedColors.put("rio grande", new Color(0xbbd009));
		namedColors.put("surf", new Color(0xbbd7c1));
		namedColors.put("powder ash", new Color(0xbcc9c2));
		namedColors.put("tuscany", new Color(0xbd5e2e));
		namedColors.put("quicksand", new Color(0xbd978e));
		namedColors.put("silk", new Color(0xbdb1a8));
		namedColors.put("malta", new Color(0xbdb2a1));
		namedColors.put("chatelle", new Color(0xbdb3c7));
		namedColors.put("lavender gray", new Color(0xbdbbd7));
		namedColors.put("french gray", new Color(0xbdbdc6));
		namedColors.put("clay ash", new Color(0xbdc8b3));
		namedColors.put("loblolly", new Color(0xbdc9ce));
		namedColors.put("french pass", new Color(0xbdedfd));
		namedColors.put("london hue", new Color(0xbea6c3));
		namedColors.put("pink swan", new Color(0xbeb5b7));
		namedColors.put("fuego", new Color(0xbede0d));
		namedColors.put("rose of sharon", new Color(0xbf5500));
		namedColors.put("tide", new Color(0xbfb8b0));
		namedColors.put("blue haze", new Color(0xbfbed8));
		namedColors.put("silver sand", new Color(0xbfc1c2));
		namedColors.put("key lime pie", new Color(0xbfc921));
		namedColors.put("ziggurat", new Color(0xbfdbe2));
		namedColors.put("lime", new Color(0xbfff00));
		namedColors.put("thunderbird", new Color(0xc02b18));
		namedColors.put("mojo", new Color(0xc04737));
		namedColors.put("old rose", new Color(0xc08081));
		namedColors.put("silver", new Color(0xc0c0c0));
		namedColors.put("pale leaf", new Color(0xc0d3b9));
		namedColors.put("pixie green", new Color(0xc0d8b6));
		namedColors.put("tia maria", new Color(0xc1440e));
		namedColors.put("fuchsia pink", new Color(0xc154c1));
		namedColors.put("buddha gold", new Color(0xc1a004));
		namedColors.put("bison hide", new Color(0xc1b7a4));
		namedColors.put("tea", new Color(0xc1bab0));
		namedColors.put("gray suit", new Color(0xc1becd));
		namedColors.put("sprout", new Color(0xc1d7b0));
		namedColors.put("sulu", new Color(0xc1f07c));
		namedColors.put("indochine", new Color(0xc26b03));
		namedColors.put("twine", new Color(0xc2955d));
		namedColors.put("cotton seed", new Color(0xc2bdb6));
		namedColors.put("pumice", new Color(0xc2cac4));
		namedColors.put("jagged ice", new Color(0xc2e8e5));
		namedColors.put("maroon flush", new Color(0xc32148));
		namedColors.put("indian khaki", new Color(0xc3b091));
		namedColors.put("pale slate", new Color(0xc3bfc1));
		namedColors.put("gray nickel", new Color(0xc3c3bd));
		namedColors.put("periwinkle gray", new Color(0xc3cde6));
		namedColors.put("tiara", new Color(0xc3d1d1));
		namedColors.put("tropical blue", new Color(0xc3ddf9));
		namedColors.put("cardinal", new Color(0xc41e3a));
		namedColors.put("fuzzy wuzzy brown", new Color(0xc45655));
		namedColors.put("orange roughy", new Color(0xc45719));
		namedColors.put("mist gray", new Color(0xc4c4bc));
		namedColors.put("coriander", new Color(0xc4d0b0));
		namedColors.put("mint tulip", new Color(0xc4f4eb));
		namedColors.put("mulberry", new Color(0xc54b8c));
		namedColors.put("nugget", new Color(0xc59922));
		namedColors.put("tussock", new Color(0xc5994b));
		namedColors.put("sea mist", new Color(0xc5dbca));
		namedColors.put("yellow green", new Color(0xc5e17a));
		namedColors.put("brick red", new Color(0xc62d42));
		namedColors.put("contessa", new Color(0xc6726b));
		namedColors.put("oriental pink", new Color(0xc69191));
		namedColors.put("roti", new Color(0xc6a84b));
		namedColors.put("ash", new Color(0xc6c3b5));
		namedColors.put("kangaroo", new Color(0xc6c8bd));
		namedColors.put("las palmas", new Color(0xc6e610));
		namedColors.put("monza", new Color(0xc7031e));
		namedColors.put("red violet", new Color(0xc71585));
		namedColors.put("coral reef", new Color(0xc7bca2));
		namedColors.put("melrose", new Color(0xc7c1ff));
		namedColors.put("cloud", new Color(0xc7c4bf));
		namedColors.put("ghost", new Color(0xc7c9d5));
		namedColors.put("pine glade", new Color(0xc7cd90));
		namedColors.put("botticelli", new Color(0xc7dde5));
		namedColors.put("antique brass", new Color(0xc88a65));
		namedColors.put("lilac", new Color(0xc8a2c8));
		namedColors.put("hokey pokey", new Color(0xc8a528));
		namedColors.put("lily", new Color(0xc8aabf));
		namedColors.put("laser", new Color(0xc8b568));
		namedColors.put("edgewater", new Color(0xc8e3d7));
		namedColors.put("piper", new Color(0xc96323));
		namedColors.put("pizza", new Color(0xc99415));
		namedColors.put("light wisteria", new Color(0xc9a0dc));
		namedColors.put("rodeo dust", new Color(0xc9b29b));
		namedColors.put("sundance", new Color(0xc9b35b));
		namedColors.put("earls green", new Color(0xc9b93b));
		namedColors.put("silver rust", new Color(0xc9c0bb));
		namedColors.put("conch", new Color(0xc9d9d2));
		namedColors.put("reef", new Color(0xc9ffa2));
		namedColors.put("aero blue", new Color(0xc9ffe5));
		namedColors.put("flush mahogany", new Color(0xca3435));
		namedColors.put("turmeric", new Color(0xcabb48));
		namedColors.put("paris white", new Color(0xcadcd4));
		namedColors.put("bitter lemon", new Color(0xcae00d));
		namedColors.put("skeptic", new Color(0xcae6da));
		namedColors.put("viola", new Color(0xcb8fa9));
		namedColors.put("foggy gray", new Color(0xcbcab6));
		namedColors.put("green mist", new Color(0xcbd3b0));
		namedColors.put("nebula", new Color(0xcbdbd6));
		namedColors.put("persian red", new Color(0xcc3333));
		namedColors.put("burnt orange", new Color(0xcc5500));
		namedColors.put("ochre", new Color(0xcc7722));
		namedColors.put("puce", new Color(0xcc8899));
		namedColors.put("thistle green", new Color(0xcccaa8));
		namedColors.put("periwinkle", new Color(0xccccff));
		namedColors.put("electric lime", new Color(0xccff00));
		namedColors.put("tenn", new Color(0xcd5700));
		namedColors.put("chestnut rose", new Color(0xcd5c5c));
		namedColors.put("brandy punch", new Color(0xcd8429));
		namedColors.put("onahau", new Color(0xcdf4ff));
		namedColors.put("sorrell brown", new Color(0xceb98f));
		namedColors.put("cold turkey", new Color(0xcebaba));
		namedColors.put("yuma", new Color(0xcec291));
		namedColors.put("chino", new Color(0xcec7a7));
		namedColors.put("eunry", new Color(0xcfa39d));
		namedColors.put("old gold", new Color(0xcfb53b));
		namedColors.put("tasman", new Color(0xcfdccf));
		namedColors.put("surf crest", new Color(0xcfe5d2));
		namedColors.put("humming bird", new Color(0xcff9f3));
		namedColors.put("scandal", new Color(0xcffaf4));
		namedColors.put("red stage", new Color(0xd05f04));
		namedColors.put("hopbush", new Color(0xd06da1));
		namedColors.put("meteor", new Color(0xd07d12));
		namedColors.put("perfume", new Color(0xd0bef8));
		namedColors.put("prelude", new Color(0xd0c0e5));
		namedColors.put("tea green", new Color(0xd0f0c0));
		namedColors.put("geebung", new Color(0xd18f1b));
		namedColors.put("vanilla", new Color(0xd1bea8));
		namedColors.put("soft amber", new Color(0xd1c6b4));
		namedColors.put("celeste", new Color(0xd1d2ca));
		namedColors.put("mischka", new Color(0xd1d2dd));
		namedColors.put("pear", new Color(0xd1e231));
		namedColors.put("hot cinnamon", new Color(0xd2691e));
		namedColors.put("raw sienna", new Color(0xd27d46));
		namedColors.put("careys pink", new Color(0xd29eaa));
		namedColors.put("tan", new Color(0xd2b48c));
		namedColors.put("deco", new Color(0xd2da97));
		namedColors.put("blue romance", new Color(0xd2f6de));
		namedColors.put("gossip", new Color(0xd2f8b0));
		namedColors.put("sisal", new Color(0xd3cbba));
		namedColors.put("swirl", new Color(0xd3cdc5));
		namedColors.put("charm", new Color(0xd47494));
		namedColors.put("clam shell", new Color(0xd4b6af));
		namedColors.put("straw", new Color(0xd4bf8d));
		namedColors.put("akaroa", new Color(0xd4c4a8));
		namedColors.put("bird flower", new Color(0xd4cd16));
		namedColors.put("iron", new Color(0xd4d7d9));
		namedColors.put("geyser", new Color(0xd4dfe2));
		namedColors.put("hawkes blue", new Color(0xd4e2fc));
		namedColors.put("grenadier", new Color(0xd54600));
		namedColors.put("can can", new Color(0xd591a4));
		namedColors.put("whiskey", new Color(0xd59a6f));
		namedColors.put("winter hazel", new Color(0xd5d195));
		namedColors.put("granny apple", new Color(0xd5f6e3));
		namedColors.put("my pink", new Color(0xd69188));
		namedColors.put("tacha", new Color(0xd6c562));
		namedColors.put("moon raker", new Color(0xd6cef6));
		namedColors.put("quill gray", new Color(0xd6d6d1));
		namedColors.put("snowy mint", new Color(0xd6ffdb));
		namedColors.put("new york pink", new Color(0xd7837f));
		namedColors.put("pavlova", new Color(0xd7c498));
		namedColors.put("fog", new Color(0xd7d0ff));
		namedColors.put("valencia", new Color(0xd84437));
		namedColors.put("japonica", new Color(0xd87c63));
		namedColors.put("thistle", new Color(0xd8bfd8));
		namedColors.put("maverick", new Color(0xd8c2d5));
		namedColors.put("foam", new Color(0xd8fcfa));
		namedColors.put("cabaret", new Color(0xd94972));
		namedColors.put("burning sand", new Color(0xd99376));
		namedColors.put("cameo", new Color(0xd9b99b));
		namedColors.put("timberwolf", new Color(0xd9d6cf));
		namedColors.put("tana", new Color(0xd9dcc1));
		namedColors.put("link water", new Color(0xd9e4f5));
		namedColors.put("mabel", new Color(0xd9f7ff));
		namedColors.put("cerise", new Color(0xda3287));
		namedColors.put("flame pea", new Color(0xda5b38));
		namedColors.put("bamboo", new Color(0xda6304));
		namedColors.put("red damask", new Color(0xda6a41));
		namedColors.put("orchid", new Color(0xda70d6));
		namedColors.put("copperfield", new Color(0xda8a67));
		namedColors.put("golden grass", new Color(0xdaa520));
		namedColors.put("zanah", new Color(0xdaecd6));
		namedColors.put("iceberg", new Color(0xdaf4f0));
		namedColors.put("oyster bay", new Color(0xdafaff));
		namedColors.put("cranberry", new Color(0xdb5079));
		namedColors.put("petite orchid", new Color(0xdb9690));
		namedColors.put("di serria", new Color(0xdb995e));
		namedColors.put("alto", new Color(0xdbdbdb));
		namedColors.put("frosted mint", new Color(0xdbfff8));
		namedColors.put("crimson", new Color(0xdc143c));
		namedColors.put("punch", new Color(0xdc4333));
		namedColors.put("galliano", new Color(0xdcb20c));
		namedColors.put("blossom", new Color(0xdcb4bc));
		namedColors.put("wattle", new Color(0xdcd747));
		namedColors.put("westar", new Color(0xdcd9d2));
		namedColors.put("moon mist", new Color(0xdcddcc));
		namedColors.put("caper", new Color(0xdcedb4));
		namedColors.put("swans down", new Color(0xdcf0ea));
		namedColors.put("swiss coffee", new Color(0xddd6d5));
		namedColors.put("white ice", new Color(0xddf9f1));
		namedColors.put("cerise red", new Color(0xde3163));
		namedColors.put("roman", new Color(0xde6360));
		namedColors.put("tumbleweed", new Color(0xdea681));
		namedColors.put("gold tips", new Color(0xdeba13));
		namedColors.put("brandy", new Color(0xdec196));
		namedColors.put("wafer", new Color(0xdecbc6));
		namedColors.put("sapling", new Color(0xded4a4));
		namedColors.put("barberry", new Color(0xded717));
		namedColors.put("beryl green", new Color(0xdee5c0));
		namedColors.put("pattens blue", new Color(0xdef5ff));
		namedColors.put("heliotrope", new Color(0xdf73ff));
		namedColors.put("apache", new Color(0xdfbe6f));
		namedColors.put("chenin", new Color(0xdfcd6f));
		namedColors.put("lola", new Color(0xdfcfdb));
		namedColors.put("willow brook", new Color(0xdfecda));
		namedColors.put("chartreuse yellow", new Color(0xdfff00));
		namedColors.put("mauve", new Color(0xe0b0ff));
		namedColors.put("anzac", new Color(0xe0b646));
		namedColors.put("harvest gold", new Color(0xe0b974));
		namedColors.put("calico", new Color(0xe0c095));
		namedColors.put("baby blue", new Color(0xe0ffff));
		namedColors.put("sunglo", new Color(0xe16865));
		namedColors.put("equator", new Color(0xe1bc64));
		namedColors.put("pink flare", new Color(0xe1c0c8));
		namedColors.put("periglacial blue", new Color(0xe1e6d6));
		namedColors.put("kidnapper", new Color(0xe1ead4));
		namedColors.put("tara", new Color(0xe1f6e8));
		namedColors.put("mandy", new Color(0xe25465));
		namedColors.put("terracotta", new Color(0xe2725b));
		namedColors.put("golden bell", new Color(0xe28913));
		namedColors.put("shocking", new Color(0xe292c0));
		namedColors.put("dixie", new Color(0xe29418));
		namedColors.put("light orchid", new Color(0xe29cd2));
		namedColors.put("snuff", new Color(0xe2d8ed));
		namedColors.put("mystic", new Color(0xe2ebed));
		namedColors.put("apple green", new Color(0xe2f3ec));
		namedColors.put("razzmatazz", new Color(0xe30b5c));
		namedColors.put("alizarin crimson", new Color(0xe32636));
		namedColors.put("cinnabar", new Color(0xe34234));
		namedColors.put("cavern pink", new Color(0xe3bebe));
		namedColors.put("peppermint", new Color(0xe3f5e1));
		namedColors.put("mindaro", new Color(0xe3f988));
		namedColors.put("deep blush", new Color(0xe47698));
		namedColors.put("gamboge", new Color(0xe49b0f));
		namedColors.put("melanie", new Color(0xe4c2d5));
		namedColors.put("twilight", new Color(0xe4cfde));
		namedColors.put("bone", new Color(0xe4d1c0));
		namedColors.put("sunflower", new Color(0xe4d422));
		namedColors.put("grain brown", new Color(0xe4d5b7));
		namedColors.put("zombie", new Color(0xe4d69b));
		namedColors.put("frostee", new Color(0xe4f6e7));
		namedColors.put("snow flurry", new Color(0xe4ffd1));
		namedColors.put("amaranth", new Color(0xe52b50));
		namedColors.put("zest", new Color(0xe5841b));
		namedColors.put("dust storm", new Color(0xe5ccc9));
		namedColors.put("stark white", new Color(0xe5d7bd));
		namedColors.put("hampton", new Color(0xe5d8af));
		namedColors.put("bon jour", new Color(0xe5e0e1));
		namedColors.put("mercury", new Color(0xe5e5e5));
		namedColors.put("polar", new Color(0xe5f9f6));
		namedColors.put("trinidad", new Color(0xe64e03));
		namedColors.put("gold sand", new Color(0xe6be8a));
		namedColors.put("cashmere", new Color(0xe6bea5));
		namedColors.put("double spanish white", new Color(0xe6d7b9));
		namedColors.put("satin linen", new Color(0xe6e4d4));
		namedColors.put("harp", new Color(0xe6f2ea));
		namedColors.put("off green", new Color(0xe6f8f3));
		namedColors.put("hint of green", new Color(0xe6ffe9));
		namedColors.put("tranquil", new Color(0xe6ffff));
		namedColors.put("mango tango", new Color(0xe77200));
		namedColors.put("christine", new Color(0xe7730a));
		namedColors.put("tonys pink", new Color(0xe79f8c));
		namedColors.put("kobi", new Color(0xe79fc4));
		namedColors.put("rose fog", new Color(0xe7bcb4));
		namedColors.put("corn", new Color(0xe7bf05));
		namedColors.put("putty", new Color(0xe7cd8c));
		namedColors.put("gray nurse", new Color(0xe7ece6));
		namedColors.put("lily white", new Color(0xe7f8ff));
		namedColors.put("bubbles", new Color(0xe7feff));
		namedColors.put("fire bush", new Color(0xe89928));
		namedColors.put("shilo", new Color(0xe8b9b3));
		namedColors.put("pearl bush", new Color(0xe8e0d5));
		namedColors.put("green white", new Color(0xe8ebe0));
		namedColors.put("chrome white", new Color(0xe8f1d4));
		namedColors.put("gin", new Color(0xe8f2eb));
		namedColors.put("aqua squeeze", new Color(0xe8f5f2));
		namedColors.put("clementine", new Color(0xe96e00));
		namedColors.put("burnt sienna", new Color(0xe97451));
		namedColors.put("tahiti gold", new Color(0xe97c07));
		namedColors.put("oyster pink", new Color(0xe9cecd));
		namedColors.put("confetti", new Color(0xe9d75a));
		namedColors.put("ebb", new Color(0xe9e3e3));
		namedColors.put("ottoman", new Color(0xe9f8ed));
		namedColors.put("clear day", new Color(0xe9fffd));
		namedColors.put("carissma", new Color(0xea88a8));
		namedColors.put("porsche", new Color(0xeaae69));
		namedColors.put("tulip tree", new Color(0xeab33b));
		namedColors.put("rob roy", new Color(0xeac674));
		namedColors.put("raffia", new Color(0xeadab8));
		namedColors.put("white rock", new Color(0xeae8d4));
		namedColors.put("panache", new Color(0xeaf6ee));
		namedColors.put("solitude", new Color(0xeaf6ff));
		namedColors.put("aqua spring", new Color(0xeaf9f5));
		namedColors.put("dew", new Color(0xeafffe));
		namedColors.put("apricot", new Color(0xeb9373));
		namedColors.put("zinnwaldite", new Color(0xebc2af));
		namedColors.put("fuel yellow", new Color(0xeca927));
		namedColors.put("ronchi", new Color(0xecc54e));
		namedColors.put("french lilac", new Color(0xecc7ee));
		namedColors.put("just right", new Color(0xeccdb9));
		namedColors.put("wild rice", new Color(0xece090));
		namedColors.put("fall green", new Color(0xecebbd));
		namedColors.put("aths special", new Color(0xecebce));
		namedColors.put("starship", new Color(0xecf245));
		namedColors.put("red ribbon", new Color(0xed0a3f));
		namedColors.put("tango", new Color(0xed7a1c));
		namedColors.put("carrot orange", new Color(0xed9121));
		namedColors.put("sea pink", new Color(0xed989e));
		namedColors.put("tacao", new Color(0xedb381));
		namedColors.put("desert sand", new Color(0xedc9af));
		namedColors.put("pancho", new Color(0xedcdab));
		namedColors.put("chamois", new Color(0xeddcb1));
		namedColors.put("primrose", new Color(0xedea99));
		namedColors.put("frost", new Color(0xedf5dd));
		namedColors.put("aqua haze", new Color(0xedf5f5));
		namedColors.put("zumthor", new Color(0xedf6ff));
		namedColors.put("narvik", new Color(0xedf9f1));
		namedColors.put("honeysuckle", new Color(0xedfc84));
		namedColors.put("lavender magenta", new Color(0xee82ee));
		namedColors.put("beauty bush", new Color(0xeec1be));
		namedColors.put("chalky", new Color(0xeed794));
		namedColors.put("almond", new Color(0xeed9c4));
		namedColors.put("flax", new Color(0xeedc82));
		namedColors.put("bizarre", new Color(0xeededa));
		namedColors.put("double colonial white", new Color(0xeee3ad));
		namedColors.put("cararra", new Color(0xeeeee8));
		namedColors.put("manz", new Color(0xeeef78));
		namedColors.put("tahuna sands", new Color(0xeef0c8));
		namedColors.put("athens gray", new Color(0xeef0f3));
		namedColors.put("tusk", new Color(0xeef3c3));
		namedColors.put("loafer", new Color(0xeef4de));
		namedColors.put("catskill white", new Color(0xeef6f7));
		namedColors.put("twilight blue", new Color(0xeefdff));
		namedColors.put("jonquil", new Color(0xeeff9a));
		namedColors.put("rice flower", new Color(0xeeffe2));
		namedColors.put("jaffa", new Color(0xef863f));
		namedColors.put("gallery", new Color(0xefefef));
		namedColors.put("porcelain", new Color(0xeff2f3));
		namedColors.put("mauvelous", new Color(0xf091a9));
		namedColors.put("golden dream", new Color(0xf0d52d));
		namedColors.put("golden sand", new Color(0xf0db7d));
		namedColors.put("buff", new Color(0xf0dc82));
		namedColors.put("prim", new Color(0xf0e2ec));
		namedColors.put("khaki", new Color(0xf0e68c));
		namedColors.put("selago", new Color(0xf0eefd));
		namedColors.put("titan white", new Color(0xf0eeff));
		namedColors.put("alice blue", new Color(0xf0f8ff));
		namedColors.put("feta", new Color(0xf0fcea));
		namedColors.put("gold drop", new Color(0xf18200));
		namedColors.put("wewak", new Color(0xf19bab));
		namedColors.put("sahara sand", new Color(0xf1e788));
		namedColors.put("parchment", new Color(0xf1e9d2));
		namedColors.put("blue chalk", new Color(0xf1e9ff));
		namedColors.put("mint julep", new Color(0xf1eec1));
		namedColors.put("seashell", new Color(0xf1f1f1));
		namedColors.put("saltpan", new Color(0xf1f7f2));
		namedColors.put("tidal", new Color(0xf1ffad));
		namedColors.put("chiffon", new Color(0xf1ffc8));
		namedColors.put("flamingo", new Color(0xf2552a));
		namedColors.put("tangerine", new Color(0xf28500));
		namedColors.put("mandys pink", new Color(0xf2c3b2));
		namedColors.put("concrete", new Color(0xf2f2f2));
		namedColors.put("black squeeze", new Color(0xf2fafa));
		namedColors.put("pomegranate", new Color(0xf34723));
		namedColors.put("buttercup", new Color(0xf3ad16));
		namedColors.put("new orleans", new Color(0xf3d69d));
		namedColors.put("vanilla ice", new Color(0xf3d9df));
		namedColors.put("sidecar", new Color(0xf3e7bb));
		namedColors.put("dawn pink", new Color(0xf3e9e5));
		namedColors.put("wheatfield", new Color(0xf3edcf));
		namedColors.put("canary", new Color(0xf3fb62));
		namedColors.put("orinoco", new Color(0xf3fbd4));
		namedColors.put("carla", new Color(0xf3ffd8));
		namedColors.put("hollywood cerise", new Color(0xf400a1));
		namedColors.put("sandy brown", new Color(0xf4a460));
		namedColors.put("saffron", new Color(0xf4c430));
		namedColors.put("ripe lemon", new Color(0xf4d81c));
		namedColors.put("janna", new Color(0xf4ebd3));
		namedColors.put("pampas", new Color(0xf4f2ee));
		namedColors.put("wild sand", new Color(0xf4f4f4));
		namedColors.put("zircon", new Color(0xf4f8ff));
		namedColors.put("froly", new Color(0xf57584));
		namedColors.put("cream can", new Color(0xf5c85c));
		namedColors.put("manhattan", new Color(0xf5c999));
		namedColors.put("maize", new Color(0xf5d5a0));
		namedColors.put("wheat", new Color(0xf5deb3));
		namedColors.put("sandwisp", new Color(0xf5e7a2));
		namedColors.put("pot pourri", new Color(0xf5e7e2));
		namedColors.put("albescent white", new Color(0xf5e9d3));
		namedColors.put("soft peach", new Color(0xf5edef));
		namedColors.put("ecru white", new Color(0xf5f3e5));
		namedColors.put("beige", new Color(0xf5f5dc));
		namedColors.put("golden fizz", new Color(0xf5fb3d));
		namedColors.put("australian mint", new Color(0xf5ffbe));
		namedColors.put("french rose", new Color(0xf64a8a));
		namedColors.put("brilliant rose", new Color(0xf653a6));
		namedColors.put("illusion", new Color(0xf6a4c9));
		namedColors.put("merino", new Color(0xf6f0e6));
		namedColors.put("black haze", new Color(0xf6f7f7));
		namedColors.put("spring sun", new Color(0xf6ffdc));
		namedColors.put("violet red", new Color(0xf7468a));
		namedColors.put("chilean fire", new Color(0xf77703));
		namedColors.put("persian pink", new Color(0xf77fbe));
		namedColors.put("rajah", new Color(0xf7b668));
		namedColors.put("azalea", new Color(0xf7c8da));
		namedColors.put("we peep", new Color(0xf7dbe6));
		namedColors.put("quarter spanish white", new Color(0xf7f2e1));
		namedColors.put("whisper", new Color(0xf7f5fa));
		namedColors.put("snow drift", new Color(0xf7faf7));
		namedColors.put("casablanca", new Color(0xf8b853));
		namedColors.put("chantilly", new Color(0xf8c3df));
		namedColors.put("cherub", new Color(0xf8d9e9));
		namedColors.put("marzipan", new Color(0xf8db9d));
		namedColors.put("energy yellow", new Color(0xf8dd5c));
		namedColors.put("givry", new Color(0xf8e4bf));
		namedColors.put("white linen", new Color(0xf8f0e8));
		namedColors.put("magnolia", new Color(0xf8f4ff));
		namedColors.put("spring wood", new Color(0xf8f6f1));
		namedColors.put("coconut cream", new Color(0xf8f7dc));
		namedColors.put("white lilac", new Color(0xf8f7fc));
		namedColors.put("desert storm", new Color(0xf8f8f7));
		namedColors.put("texas", new Color(0xf8f99c));
		namedColors.put("corn field", new Color(0xf8facd));
		namedColors.put("mimosa", new Color(0xf8fdd3));
		namedColors.put("carnation", new Color(0xf95a61));
		namedColors.put("saffron mango", new Color(0xf9bf58));
		namedColors.put("carousel pink", new Color(0xf9e0ed));
		namedColors.put("dairy cream", new Color(0xf9e4bc));
		namedColors.put("portica", new Color(0xf9e663));
		namedColors.put("amour", new Color(0xf9eaf3));
		namedColors.put("rum swizzle", new Color(0xf9f8e4));
		namedColors.put("dolly", new Color(0xf9ff8b));
		namedColors.put("sugar cane", new Color(0xf9fff6));
		namedColors.put("ecstasy", new Color(0xfa7814));
		namedColors.put("tan hide", new Color(0xfa9d5a));
		namedColors.put("corvette", new Color(0xfad3a2));
		namedColors.put("peach yellow", new Color(0xfadfad));
		namedColors.put("turbo", new Color(0xfae600));
		namedColors.put("astra", new Color(0xfaeab9));
		namedColors.put("champagne", new Color(0xfaeccc));
		namedColors.put("linen", new Color(0xfaf0e6));
		namedColors.put("fantasy", new Color(0xfaf3f0));
		namedColors.put("citrine white", new Color(0xfaf7d6));
		namedColors.put("alabaster", new Color(0xfafafa));
		namedColors.put("hint of yellow", new Color(0xfafde4));
		namedColors.put("milan", new Color(0xfaffa4));
		namedColors.put("brink pink", new Color(0xfb607f));
		namedColors.put("geraldine", new Color(0xfb8989));
		namedColors.put("lavender rose", new Color(0xfba0e3));
		namedColors.put("sea buckthorn", new Color(0xfba129));
		namedColors.put("sun", new Color(0xfbac13));
		namedColors.put("lavender pink", new Color(0xfbaed2));
		namedColors.put("rose bud", new Color(0xfbb2a3));
		namedColors.put("cupid", new Color(0xfbbeda));
		namedColors.put("classic rose", new Color(0xfbcce7));
		namedColors.put("apricot peach", new Color(0xfbceb1));
		namedColors.put("banana mania", new Color(0xfbe7b2));
		namedColors.put("marigold yellow", new Color(0xfbe870));
		namedColors.put("festival", new Color(0xfbe96c));
		namedColors.put("sweet corn", new Color(0xfbea8c));
		namedColors.put("candy corn", new Color(0xfbec5d));
		namedColors.put("hint of red", new Color(0xfbf9f9));
		namedColors.put("shalimar", new Color(0xfbffba));
		namedColors.put("shocking pink", new Color(0xfc0fc0));
		namedColors.put("tickle me pink", new Color(0xfc80a5));
		namedColors.put("tree poppy", new Color(0xfc9c1d));
		namedColors.put("lightning yellow", new Color(0xfcc01e));
		namedColors.put("goldenrod", new Color(0xfcd667));
		namedColors.put("candlelight", new Color(0xfcd917));
		namedColors.put("cherokee", new Color(0xfcda98));
		namedColors.put("double pearl lusta", new Color(0xfcf4d0));
		namedColors.put("pearl lusta", new Color(0xfcf4dc));
		namedColors.put("vista white", new Color(0xfcf8f7));
		namedColors.put("bianca", new Color(0xfcfbf3));
		namedColors.put("moon glow", new Color(0xfcfeda));
		namedColors.put("china ivory", new Color(0xfcffe7));
		namedColors.put("ceramic", new Color(0xfcfff9));
		namedColors.put("torch red", new Color(0xfd0e35));
		namedColors.put("wild watermelon", new Color(0xfd5b78));
		namedColors.put("crusta", new Color(0xfd7b33));
		namedColors.put("sorbus", new Color(0xfd7c07));
		namedColors.put("sweet pink", new Color(0xfd9fa2));
		namedColors.put("light apricot", new Color(0xfdd5b1));
		namedColors.put("pig pink", new Color(0xfdd7e4));
		namedColors.put("cinderella", new Color(0xfde1dc));
		namedColors.put("golden glow", new Color(0xfde295));
		namedColors.put("lemon", new Color(0xfde910));
		namedColors.put("old lace", new Color(0xfdf5e6));
		namedColors.put("half colonial white", new Color(0xfdf6d3));
		namedColors.put("drover", new Color(0xfdf7ad));
		namedColors.put("pale prim", new Color(0xfdfeb8));
		namedColors.put("cumulus", new Color(0xfdffd5));
		namedColors.put("persian rose", new Color(0xfe28a2));
		namedColors.put("sunset orange", new Color(0xfe4c40));
		namedColors.put("bittersweet", new Color(0xfe6f5e));
		namedColors.put("california", new Color(0xfe9d04));
		namedColors.put("yellow sea", new Color(0xfea904));
		namedColors.put("melon", new Color(0xfebaad));
		namedColors.put("bright sun", new Color(0xfed33c));
		namedColors.put("dandelion", new Color(0xfed85d));
		namedColors.put("salomie", new Color(0xfedb8d));
		namedColors.put("cape honey", new Color(0xfee5ac));
		namedColors.put("remy", new Color(0xfeebf3));
		namedColors.put("oasis", new Color(0xfeefce));
		namedColors.put("bridesmaid", new Color(0xfef0ec));
		namedColors.put("beeswax", new Color(0xfef2c7));
		namedColors.put("bleach white", new Color(0xfef3d8));
		namedColors.put("pipi", new Color(0xfef4cc));
		namedColors.put("half spanish white", new Color(0xfef4db));
		namedColors.put("wisp pink", new Color(0xfef4f8));
		namedColors.put("provincial pink", new Color(0xfef5f1));
		namedColors.put("half dutch white", new Color(0xfef7de));
		namedColors.put("solitaire", new Color(0xfef8e2));
		namedColors.put("white pointer", new Color(0xfef8ff));
		namedColors.put("off yellow", new Color(0xfef9e3));
		namedColors.put("orange white", new Color(0xfefced));
		namedColors.put("red", new Color(0xff0000));
		namedColors.put("rose", new Color(0xff007f));
		namedColors.put("purple pizzazz", new Color(0xff00cc));
		namedColors.put("magenta / fuchsia", new Color(0xff00ff));
		namedColors.put("scarlet", new Color(0xff2400));
		namedColors.put("wild strawberry", new Color(0xff3399));
		namedColors.put("razzle dazzle rose", new Color(0xff33cc));
		namedColors.put("radical red", new Color(0xff355e));
		namedColors.put("red orange", new Color(0xff3f34));
		namedColors.put("coral red", new Color(0xff4040));
		namedColors.put("vermilion", new Color(0xff4d00));
		namedColors.put("international orange", new Color(0xff4f00));
		namedColors.put("outrageous orange", new Color(0xff6037));
		namedColors.put("blaze orange", new Color(0xff6600));
		namedColors.put("pink flamingo", new Color(0xff66ff));
		namedColors.put("orange", new Color(0xff681f));
		namedColors.put("hot pink", new Color(0xff69b4));
		namedColors.put("persimmon", new Color(0xff6b53));
		namedColors.put("blush pink", new Color(0xff6fff));
		namedColors.put("burning orange", new Color(0xff7034));
		namedColors.put("pumpkin", new Color(0xff7518));
		namedColors.put("flamenco", new Color(0xff7d07));
		namedColors.put("flush orange", new Color(0xff7f00));
		namedColors.put("coral", new Color(0xff7f50));
		namedColors.put("salmon", new Color(0xff8c69));
		namedColors.put("pizazz", new Color(0xff9000));
		namedColors.put("west side", new Color(0xff910f));
		namedColors.put("pink salmon", new Color(0xff91a4));
		namedColors.put("neon carrot", new Color(0xff9933));
		namedColors.put("atomic tangerine", new Color(0xff9966));
		namedColors.put("vivid tangerine", new Color(0xff9980));
		namedColors.put("sunshade", new Color(0xff9e2c));
		namedColors.put("orange peel", new Color(0xffa000));
		namedColors.put("mona lisa", new Color(0xffa194));
		namedColors.put("web orange", new Color(0xffa500));
		namedColors.put("carnation pink", new Color(0xffa6c9));
		namedColors.put("hit pink", new Color(0xffab81));
		namedColors.put("yellow orange", new Color(0xffae42));
		namedColors.put("cornflower lilac", new Color(0xffb0ac));
		namedColors.put("sundown", new Color(0xffb1b3));
		namedColors.put("my sin", new Color(0xffb31f));
		namedColors.put("texas rose", new Color(0xffb555));
		namedColors.put("cotton candy", new Color(0xffb7d5));
		namedColors.put("macaroni and cheese", new Color(0xffb97b));
		namedColors.put("selective yellow", new Color(0xffba00));
		namedColors.put("koromiko", new Color(0xffbd5f));
		namedColors.put("amber", new Color(0xffbf00));
		namedColors.put("wax flower", new Color(0xffc0a8));
		namedColors.put("pink", new Color(0xffc0cb));
		namedColors.put("your pink", new Color(0xffc3c0));
		namedColors.put("supernova", new Color(0xffc901));
		namedColors.put("flesh", new Color(0xffcba4));
		namedColors.put("sunglow", new Color(0xffcc33));
		namedColors.put("golden tainoi", new Color(0xffcc5c));
		namedColors.put("peach orange", new Color(0xffcc99));
		namedColors.put("chardonnay", new Color(0xffcd8c));
		namedColors.put("pastel pink", new Color(0xffd1dc));
		namedColors.put("romantic", new Color(0xffd2b7));
		namedColors.put("grandis", new Color(0xffd38c));
		namedColors.put("gold", new Color(0xffd700));
		namedColors.put("school bus yellow", new Color(0xffd800));
		namedColors.put("cosmos", new Color(0xffd8d9));
		namedColors.put("mustard", new Color(0xffdb58));
		namedColors.put("peach schnapps", new Color(0xffdcd6));
		namedColors.put("caramel", new Color(0xffddaf));
		namedColors.put("tuft bush", new Color(0xffddcd));
		namedColors.put("watusi", new Color(0xffddcf));
		namedColors.put("pink lace", new Color(0xffddf4));
		namedColors.put("navajo white", new Color(0xffdead));
		namedColors.put("frangipani", new Color(0xffdeb3));
		namedColors.put("pippin", new Color(0xffe1df));
		namedColors.put("pale rose", new Color(0xffe1f2));
		namedColors.put("negroni", new Color(0xffe2c5));
		namedColors.put("cream brulee", new Color(0xffe5a0));
		namedColors.put("peach", new Color(0xffe5b4));
		namedColors.put("tequila", new Color(0xffe6c7));
		namedColors.put("kournikova", new Color(0xffe772));
		namedColors.put("sandy beach", new Color(0xffeac8));
		namedColors.put("karry", new Color(0xffead4));
		namedColors.put("broom", new Color(0xffec13));
		namedColors.put("colonial white", new Color(0xffedbc));
		namedColors.put("derby", new Color(0xffeed8));
		namedColors.put("vis vis", new Color(0xffefa1));
		namedColors.put("egg white", new Color(0xffefc1));
		namedColors.put("papaya whip", new Color(0xffefd5));
		namedColors.put("fair pink", new Color(0xffefec));
		namedColors.put("peach cream", new Color(0xfff0db));
		namedColors.put("lavender blush", new Color(0xfff0f5));
		namedColors.put("gorse", new Color(0xfff14f));
		namedColors.put("buttermilk", new Color(0xfff1b5));
		namedColors.put("pink lady", new Color(0xfff1d8));
		namedColors.put("forget me not", new Color(0xfff1ee));
		namedColors.put("tutu", new Color(0xfff1f9));
		namedColors.put("picasso", new Color(0xfff39d));
		namedColors.put("chardon", new Color(0xfff3f1));
		namedColors.put("paris daisy", new Color(0xfff46e));
		namedColors.put("barley white", new Color(0xfff4ce));
		namedColors.put("egg sour", new Color(0xfff4dd));
		namedColors.put("sazerac", new Color(0xfff4e0));
		namedColors.put("serenade", new Color(0xfff4e8));
		namedColors.put("chablis", new Color(0xfff4f3));
		namedColors.put("seashell peach", new Color(0xfff5ee));
		namedColors.put("sauvignon", new Color(0xfff5f3));
		namedColors.put("milk punch", new Color(0xfff6d4));
		namedColors.put("varden", new Color(0xfff6df));
		namedColors.put("rose white", new Color(0xfff6f5));
		namedColors.put("baja white", new Color(0xfff8d1));
		namedColors.put("gin fizz", new Color(0xfff9e2));
		namedColors.put("early dawn", new Color(0xfff9e6));
		namedColors.put("lemon chiffon", new Color(0xfffacd));
		namedColors.put("bridal heath", new Color(0xfffaf4));
		namedColors.put("scotch mist", new Color(0xfffbdc));
		namedColors.put("soapstone", new Color(0xfffbf9));
		namedColors.put("witch haze", new Color(0xfffc99));
		namedColors.put("buttery white", new Color(0xfffcea));
		namedColors.put("island spice", new Color(0xfffcee));
		namedColors.put("cream", new Color(0xfffdd0));
		namedColors.put("chilean heath", new Color(0xfffde6));
		namedColors.put("travertine", new Color(0xfffde8));
		namedColors.put("orchid white", new Color(0xfffdf3));
		namedColors.put("quarter pearl lusta", new Color(0xfffdf4));
		namedColors.put("half and half", new Color(0xfffee1));
		namedColors.put("apricot white", new Color(0xfffeec));
		namedColors.put("rice cake", new Color(0xfffef0));
		namedColors.put("black white", new Color(0xfffef6));
		namedColors.put("romance", new Color(0xfffefd));
		namedColors.put("yellow", new Color(0xffff00));
		namedColors.put("laser lemon", new Color(0xffff66));
		namedColors.put("pale canary", new Color(0xffff99));
		namedColors.put("portafino", new Color(0xffffb4));
		namedColors.put("ivory", new Color(0xfffff0));
		namedColors.put("white", new Color(0xffffff));
	}

	public static Color get(String name) {
		return namedColors.get(name.toLowerCase());
	}
}
